# Generated by Django 4.2.20 on 2025-05-01 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('night', '0002_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
