# Generated by Django 4.2.20 on 2025-05-06 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('night', '0003_alter_review_approved'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['created_on']},
        ),
    ]
